from datetime import datetime, timezone

from ragguard.finding import Finding


def write_markdown_report(findings: list[Finding], target: str, output_path: str) -> None:
    high = sum(1 for f in findings if f.severity == "HIGH")
    med = sum(1 for f in findings if f.severity == "MEDIUM")
    low = sum(1 for f in findings if f.severity == "LOW")
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# RAGGuard Security Report",
        "",
        f"**Target**: `{target}`",
        f"**Date**: {timestamp}",
        f"**Findings**: {len(findings)} ({high} high, {med} medium, {low} low)",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| HIGH     | {high}   |",
        f"| MEDIUM   | {med}   |",
        f"| LOW      | {low}   |",
        f"| **Total**| **{len(findings)}** |",
        "",
    ]

    if not findings:
        lines.append("No security findings detected.")
    else:
        lines.append("## Findings")
        lines.append("")

        for f in findings:
            cwe = f" ({f.cwe_id})" if f.cwe_id else ""
            lines.append(f"### {f.id} [{f.severity}] {f.title}{cwe}")
            lines.append("")
            lines.append(f"**File**: `{f.file_path}:{f.line_number}`")
            lines.append(f"**Category**: {f.category}")
            lines.append("")
            lines.append(f"{f.description}")
            lines.append("")
            if f.code_snippet:
                lines.append("```python")
                lines.append(f"{f.code_snippet}")
                lines.append("```")
                lines.append("")
            lines.append(f"**Remediation**: {f.remediation}")
            lines.append("")
            lines.append("---")
            lines.append("")

    lines.append("")
    lines.append("*Generated by [RAGGuard](https://github.com/HrushiYadav/ragguard)*")

    with open(output_path, "w", encoding="utf-8") as fp:
        fp.write("\n".join(lines))
